import { useSelector } from 'react-redux';
import io from 'socket.io-client';
import {
    ADD_PLAYER,
    ADD_QUESTIONS,
    UPDATE_GAME_SETTINGS,
    UPDATE_SCORE,
    UPDATE_SOCKET
} from './constants';

const players = useSelector(state => state.players);
const socket = io.connect('http://localhost:3000');

export const updateSocket = () => {
    return { type: UPDATE_SOCKET, payload: socket };
};

/**
 * @param {string} username
 * @param {number} room random number generated in NewGame page.
 * @returns action to add a new player to existing list.
 */
export const addPlayer = (username, room) => {
    const player = {
        username,
        host: !players.length ? true : false,
        totalScore: 0
    };

    return { type: ADD_PLAYER, payload: { room, player } };
};

export const updateGameSettings = (category, difficulty) => {
    return { type: UPDATE_GAME_SETTINGS, payload: { category, difficulty } };
};

/**
 * Add questions fetched from the Open Trivia API to state.
 * @param {string} category
 * @param {number} difficulty should be a number generated by a helper function
 */
export const addQuestions = (category, difficulty) => async dispatch => {
    try {
        const url = `https://opentdb.com/api.php?amount=10&category=${category}&difficulty=${difficulty}&type=multiple`;
        const { results } = await axios.get(url);
        dispatch({ type: ADD_QUESTIONS, payload: results });
    } catch (error) {
        console.error('Error fetching questions ', error);
    }
};

export const updateScore = score => {
    return { type: UPDATE_SCORE, payload: score };
};
