export const UPDATE_SOCKET = 'UPDATE_SOCKET';
export const ADD_PLAYER = 'ADD_PLAYER';
export const UPDATE_ROOM_NUMBER = 'UPDATE_ROOM_NUMBER';
export const UPDATE_GAME_SETTINGS = 'UPDATE_GAME_SETTINGS';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const CURRENT_PLAYER = 'CURRENT_PLAYER';
